import {CATALOG} from './catalog.js';
const H=parent.__HOST,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let shop={open:true,offers:[]},busy=false,offset=0;const now=()=>Date.now()+offset,fmt=n=>Number(n).toLocaleString();
function notice(s){$('message').textContent=s;$('message').style.display='block';}
async function action(input){if(busy)return null;busy=true;try{const out=await H.cloud('adminshop',input);shop=out.shop;offset=out.serverNow-Date.now();draw();return out;}catch(e){notice(e.message);return null;}finally{busy=false;}}
let shelfPage=0;
function offerDetails(o){const d=$('dialog');d.innerHTML=`<img src="images/${esc(o.image.replace(/^images\//,''))}" style="display:block;width:100px;height:100px;object-fit:contain;margin:auto"><h2>${esc(o.name)}</h2><p>แพ็กละ ${fmt(o.quantity)} ชิ้น · ${fmt(o.price)} กุศล</p><p class="timer" data-end="${o.end}"></p><label>จำนวนแพ็ก<input id="buyPacks" type="number" min="1" value="1"></label><p id="buyTotal">รวม ${fmt(o.quantity)} ชิ้น · ${fmt(o.price)} กุศล</p><div class="toolbar"><button id="confirmBuy">ซื้อ</button>${H.admin?'<button id="removeOffer">นำออก</button>':''}<button id="closeOffer">ปิด</button></div>`;d.showModal();$('closeOffer').onclick=()=>d.close();$('buyPacks').oninput=()=>{const n=Number($('buyPacks').value);$('buyTotal').textContent='รวม '+fmt(o.quantity*n)+' ชิ้น · '+fmt(o.price*n)+' กุศล';};$('confirmBuy').onclick=async()=>{const b=$('confirmBuy');b.disabled=true;const out=await action({type:'buy',offer:o.id,packs:Number($('buyPacks').value)});if(out){d.close();notice(`ซื้อ ${out.bought.name} ×${fmt(out.bought.quantity)} · หัก ${fmt(out.bought.cost)} กุศล · ของเข้ากระเป๋าและบันทึกแล้ว`);}else b.disabled=false;};if($('removeOffer'))$('removeOffer').onclick=async()=>{if(await action({type:'remove',offer:o.id}))d.close();};tick();}
function draw(){const rows=shop.offers.filter(o=>o.end>now()),pages=Math.max(1,Math.ceil(rows.length/9));shelfPage=Math.min(shelfPage,pages-1);const visible=rows.slice(shelfPage*9,shelfPage*9+9);
 $('offers').innerHTML=Array.from({length:9},(_,i)=>{const o=shop.open?visible[i]:null;return `<div class="shelf-slot" style="left:${16.2+i%3*23.3}%;top:${20.3+Math.floor(i/3)*9.2}%">${o?`<button class="shelf-item" data-buy="${esc(o.id)}" aria-label="ดู ${esc(o.name)}"><img src="images/${esc(o.image.replace(/^images\//,''))}"><b>${esc(o.name)}</b><small>${fmt(o.price)} กุศล/แพ็ก</small></button>`:''}</div>`;}).join('')+`<div class="shelf-footer">${!shop.open?'🌙 ร้านปิดอยู่':!rows.length?'ยังไม่มีสินค้าวางขายค่ะ':'แตะสินค้าบนชั้นเพื่อดูและซื้อ'}${pages>1?`<div><button id="previousShelf">‹</button> หน้า ${shelfPage+1}/${pages} <button id="nextShelf">›</button></div>`:''}</div>`;
 $('offers').querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>offerDetails(rows.find(o=>o.id===b.dataset.buy)));if($('previousShelf'))$('previousShelf').onclick=()=>{shelfPage=Math.max(0,shelfPage-1);draw();};if($('nextShelf'))$('nextShelf').onclick=()=>{shelfPage=Math.min(pages-1,shelfPage+1);draw();};tick();}
function tick(){let expired=false;document.querySelectorAll('[data-end]').forEach(el=>{const sec=Math.max(0,Math.ceil((Number(el.dataset.end)-now())/1000));el.textContent=`เหลือ ${Math.floor(sec/3600)}:${String(Math.floor(sec%3600/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(!sec)expired=true;});if(expired)draw();}
function manage(){const d=$('dialog');d.innerHTML=`<h2>👑 วางขายสินค้า</h2><label>สินค้า<select id="item">${CATALOG.filter(c=>!c.p.startsWith('pend.')).map(c=>`<option value="${esc(c.k)}">${esc(c.g)} · ${esc(c.n)}</option>`).join('')}</select></label><label>จำนวนต่อแพ็ก<input id="quantity" type="number" min="1" value="100"></label><label>กุศลต่อแพ็ก<input id="price" type="number" min="1" value="1000"></label><label>ขายกี่ชั่วโมง<input id="hours" type="number" min="0.01" step="0.01" value="6"></label><div class="toolbar"><button id="list">วางขาย</button><button id="toggle">${shop.open?'ปิดร้าน':'เปิดร้าน'}</button><button id="close">ปิดหน้าต่าง</button></div>`;d.showModal();$('close').onclick=()=>d.close();$('toggle').onclick=async()=>{if(await action({type:'open',open:!shop.open}))d.close();};$('list').onclick=async()=>{if(await action({type:'list',item:$('item').value,quantity:Number($('quantity').value),price:Number($('price').value),hours:Number($('hours').value)}))d.close();};}
$('mail').onclick=()=>H.openMail();$('manage').hidden=!H.admin;$('manage').onclick=manage;await action({type:'status'});const stop=H.watchWorld('adminshop',data=>{if(data){shop=data;draw();}});const timer=setInterval(tick,1000);addEventListener('pagehide',()=>{stop();clearInterval(timer);},{once:true});
