import {CATALOG} from './catalog.js';
const H=parent.__HOST,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let shop={open:true,offers:[]},busy=false,offset=0;const now=()=>Date.now()+offset,fmt=n=>Number(n).toLocaleString();
function notice(s){$('message').textContent=s;$('message').style.display='block';}
async function action(input){if(busy)return null;busy=true;try{const out=await H.cloud('adminshop',input);shop=out.shop;offset=out.serverNow-Date.now();draw();return out;}catch(e){notice(e.message);return null;}finally{busy=false;}}
function draw(){const rows=shop.offers.filter(o=>o.end>now());$('offers').innerHTML=!shop.open?'<div class="offer">🌙 ร้านปิดอยู่</div>':!rows.length?'<div class="offer">ยังไม่มีสินค้าวางขายค่ะ</div>':rows.map(o=>`<article class="offer" data-id="${esc(o.id)}"><img src="images/${esc(o.image)}"><b>${esc(o.name)}</b><small>แพ็กละ ${fmt(o.quantity)} ชิ้น · ${fmt(o.price)} กุศล</small><small class="timer" data-end="${o.end}"></small><input type="number" min="1" value="1" aria-label="จำนวนแพ็ก"><button data-buy="${esc(o.id)}">ซื้อ</button>${H.admin?`<button data-remove="${esc(o.id)}">นำออก</button>`:''}</article>`).join('');
 $('offers').querySelectorAll('[data-buy]').forEach(b=>b.onclick=async()=>{b.disabled=true;const out=await action({type:'buy',offer:b.dataset.buy,packs:Number(b.closest('article').querySelector('input').value)});if(out)notice(`ซื้อ ${out.bought.name} ×${fmt(out.bought.quantity)} แล้ว ของเข้ากระเป๋าและบันทึกสำเร็จ`);else b.disabled=false;});
 $('offers').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>action({type:'remove',offer:b.dataset.remove}));tick();}
function tick(){let expired=false;document.querySelectorAll('[data-end]').forEach(el=>{const sec=Math.max(0,Math.ceil((Number(el.dataset.end)-now())/1000));el.textContent=`เหลือ ${Math.floor(sec/3600)}:${String(Math.floor(sec%3600/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(!sec)expired=true;});if(expired)draw();}
function manage(){const d=$('dialog');d.innerHTML=`<h2>👑 วางขายสินค้า</h2><label>สินค้า<select id="item">${CATALOG.filter(c=>!c.p.startsWith('pend.')).map(c=>`<option value="${esc(c.k)}">${esc(c.g)} · ${esc(c.n)}</option>`).join('')}</select></label><label>จำนวนต่อแพ็ก<input id="quantity" type="number" min="1" value="100"></label><label>กุศลต่อแพ็ก<input id="price" type="number" min="1" value="1000"></label><label>ขายกี่ชั่วโมง<input id="hours" type="number" min="0.01" step="0.01" value="6"></label><div class="toolbar"><button id="list">วางขาย</button><button id="toggle">${shop.open?'ปิดร้าน':'เปิดร้าน'}</button><button id="close">ปิดหน้าต่าง</button></div>`;d.showModal();$('close').onclick=()=>d.close();$('toggle').onclick=async()=>{if(await action({type:'open',open:!shop.open}))d.close();};$('list').onclick=async()=>{if(await action({type:'list',item:$('item').value,quantity:Number($('quantity').value),price:Number($('price').value),hours:Number($('hours').value)}))d.close();};}
$('mail').onclick=()=>H.openMail();$('manage').hidden=!H.admin;$('manage').onclick=manage;await action({type:'status'});const stop=H.watchWorld('adminshop',data=>{if(data){shop=data;draw();}});const timer=setInterval(tick,1000);addEventListener('pagehide',()=>{stop();clearInterval(timer);},{once:true});
