/* Existing Preview drawing stays in scr-farm; committed vegetable actions use the cloud. */
(()=>{
 window.cloudFarmReady=true;const H=parent.__HOST,escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let busy=false,owner=null;
 async function act(type,data={}){if(busy)return;busy=true;const origins=type==='harvest'?(S.farms[farm]||[]).flatMap((p,i)=>p?.ph==='ready'&&(data.all||i===data.index)?[{crop:p.c,rect:plotEls[i]?.getBoundingClientRect()}]:[]):[];try{const before=JSON.parse(H.get('s3all-v1'));const out=await H.cloud('farm',{type,farm,...data});Object.assign(S,JSON.parse(H.get('s3all-v1')));pts=S.merit;closeAll();render();if(type==='fruit-craft'){const outputs=out.outputs,consumed=out.consumed;showCraftResult({title:'คราฟสวนผลไม้',results:out.results,outputs,consumed},()=>window.fruitCommand('fruit-craft',data));}for(const o of origins)window.harvestPop?.(IMG['p-'+o.crop]||IMG[o.crop+'4'],o.rect,1);if(out.halloween?.length){setTimeout(()=>showCraftResult({title:'🎃 รางวัลเก็บฟักทองครบ 10 แปลง',outputs:out.halloween,consumed:[]}),2900);}else if(type==='harvest'&&origins.some(o=>o.crop==='pumpkin')){setTimeout(()=>toast(out.pumpActive?'🎃 ฟักทองสะสม '+out.pumpPlots+' แปลง · อีก '+(10-out.pumpPlots%10)+' แปลงรับไอเทม':'🎃 แคมเปญฟักทองยังไม่เปิด ให้แอดมินกดเริ่มที่หน้าแคมเปญ'),500);}if(type!=='status')toast('☁️ บันทึกแล้ว'+(out.count?' • '+out.count+' แปลง':''));return out;}catch(e){toast(e.message,1);}finally{busy=false;}}
 window.farmUnlock=id=>act('unlock',{unlock:id});
 window.fruitCommand=async(type,data={})=>{const nodes=Array.from($('stage').querySelectorAll('.ftree')),origins=nodes.map(el=>({index:Number(el.dataset.index),src:el.querySelector('img.fr')?.src,rect:el.getBoundingClientRect()}));const out=await act(type,data);if(out&&type==='fruit-harvest')for(const o of (data.all?origins:[origins.find(o=>o.index===data.index)]).filter(Boolean))window.harvestPop?.(o.src,o.rect,3);return out;};
 const oldTap=tapPlot;tapPlot=async function(i){if(visiting)return friendPlot(i);const p=S.farms[farm][i];ptick(p);if(p?.magicUntil>Date.now())return toast('🔮 แปลงนี้มีมนต์ดำ รอหมดเวลาก่อน',1);if(p?.ph==='ready')return act('harvest',{index:i});if(p?.ph==='water')return act('water',{index:i});if(p?.ph==='worm')return act('worm',{index:i});oldTap(i);};
 harvest=list=>act('harvest',{all:list.length>1,index:list[0]});useOne=k=>act('boost',{index:cur,item:k});useAll=k=>act('boost',{all:true,item:k});
 $('aAngel').onclick=()=>act('angel',{index:cur});$('aDig').onclick=()=>{if(confirm('ถอนผักแปลงนี้ทิ้งใช่ไหม?'))act('dig',{index:cur});};$('gGo').onclick=()=>act('angel',{all:true});
 $('seeds').addEventListener('click',e=>{const seed=e.target.closest('.seed');if(!seed)return;e.stopImmediatePropagation();act('plant',{crop:seed.dataset.k,index:pending,all:plantAll});},true);
 $('fan').addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b||visiting||!$('fan').classList.contains('open'))return;const types={waterAll:'water',wormAll:'worm',harvestAll:'harvest'};if(b.dataset.a==='plantAll'){e.stopImmediatePropagation();plantAll=true;$('seedTitle').textContent='🌱 ปลูกทั้งหมด';closeAll();open('seedSheet');return;}if(b.dataset.a==='boostAll'){e.stopImmediatePropagation();$('bNeed').textContent='เร่งต้นที่ยังไม่พร้อมเก็บ';$('bCake').textContent='ใช้เค้ก • มี '+S.bag.item.cake;$('bCoco').textContent='ใช้มะพร้าว • มี '+S.bag.item.coconut;closeAll();open('boostSheet');return;}if(b.dataset.a==='angelAll'){e.stopImmediatePropagation();$('gNeed').textContent='ใส่ปีกให้ต้นที่ยังไม่มีปีก';$('gGo').textContent='ใส่ปีก • มี '+S.bag.item.angel;closeAll();open('angelSheet');return;}if(types[b.dataset.a]){e.stopImmediatePropagation();$('fan').classList.remove('open');$('toolBtn').classList.remove('open');act(types[b.dataset.a],{all:true});}},true);
 renderFriends=async function(){try{const rows=await H.roster();FR.length=0;rows.forEach((p,i)=>FR.push([p.name,p.merit,['#F6B43C','#A9BDD0','#E09C70','#6CC9A8'][i%4],p.uid===H.uid,0,p.uid,p.admin]));const owner=FR.filter(f=>f[6]),players=FR.filter(f=>!f[6]).sort((a,b)=>b[1]-a[1]);$('friendList').innerHTML=[...owner,...players].map((f,i)=>{const rank=i-owner.length;return '<div class="rank'+(f[3]?' me':'')+(f[6]?' owner-rank':'')+'" data-uid="'+escape(f[5])+'"><span class="no">'+(f[6]?'👑':(['🥇','🥈','🥉'][rank]||rank+1))+'</span><span class="ra" style="background:'+f[2]+'">'+escape(f[0][0])+'</span><span class="rn">'+escape(f[0])+(f[6]?' · เจ้าของสวน':f[3]?' (คุณ)':'')+'</span><span class="rp">'+(f[6]?'แอดมิน':fmt(f[1]))+'</span></div>';}).join('');}catch(e){toast(e.message,1);}};
 $('mFriend').onclick=()=>{closeAll();open('friendSheet');renderFriends();};$('friendList').onclick=e=>{const row=e.target.closest('[data-uid]');if(!row)return;const f=FR.find(f=>f[5]===row.dataset.uid);if(!f||f[3])return toast('นี่คือสวนของคุณ');$('fmAv').textContent=f[0][0];$('fmName').textContent=f[0];$('fmInfo').textContent=fmt(f[1])+' กุศล';$('fmVisit').onclick=()=>visit(f[5]);closeAll();open('friendModal');};
 function project(out){window.friendFarm=out;owner=out.owner;visiting=out.name;steals=out.quota?.steals||0;magics=out.quota?.magics||0;FRIEND_PLOTS.length=0;out.plots.forEach(p=>FRIEND_PLOTS.push(!p?'empty':p.magicUntil>Date.now()?'magic':p.angel?'angel':p.ph==='g1'||p.ph==='g2'?'grow':p.ph));$('vName').textContent=visiting;updQuota();$('visit').classList.add('on');render();}
 async function friend(type,data={}){if(busy)return;busy=true;try{const out=await H.cloud('friends',{type,owner,farm,...data});Object.assign(S,JSON.parse(H.get('s3all-v1')));pts=S.merit;project(out);if(type!=='visit')toast('☁️ บันทึกการเยี่ยมสวนแล้ว');return out;}catch(e){toast(e.message,1);}finally{busy=false;}}
 visit=async function(uid){closeAll();owner=uid;farm=1;await friend('visit');};
 const oldGo=go;go=function(d,to){if(!visiting)return oldGo(d,to);farm=Math.max(1,Math.min(4,to||farm+d));friend('visit');};
 friendPlot=function(i){const p=window.friendFarm?.plots[i],k=!p?'empty':p.magicUntil>Date.now()?'magic':p.angel?'angel':p.ph,acts=[];if(p&&!['magic','angel'].includes(k)){if(k==='ready')acts.push(['🧤 ขโมย','steal']);if(k==='water')acts.push(['💧 รดน้ำ','water']);if(k==='worm')acts.push(['🪱 กำจัดหนอน','worm']);acts.push(['🔮 เล่นของ 3 ชั่วโมง','magic']);}$('pmTitle').textContent='แปลงที่ '+(i+1)+' ของ '+visiting;$('pmMsg').textContent=!p?'แปลงว่าง':k==='magic'?'มนต์ดำเหลือ '+Math.ceil((p.magicUntil-Date.now())/60000)+' นาที':k==='angel'?'นางฟ้าปกป้องแปลงนี้':(CN[p.c]||p.c);$('pmActs').innerHTML=acts.map(([label,type])=>'<button data-a="'+type+'" data-i="'+i+'">'+label+'</button>').join('')+'<button data-a="close">ปิด</button>';open('plotModal');};
 $('pmActs').onclick=e=>{const b=e.target.closest('button');if(!b)return;closeAll();if(b.dataset.a!=='close')friend(b.dataset.a,{index:+b.dataset.i});};
 $('vHome').onclick=async()=>{visiting=null;owner=null;window.friendFarm=null;$('visit').classList.remove('on');await act('status');};
 // Refresh once on entry, not on the animation clock.
 act('status');
})();
