/* Loaded after the farm preview scripts; actions commit before the animation. */
const OutingsHost=parent.__HOST;
let outingBusy=false;
async function outingAction(input){if(outingBusy)return null;outingBusy=true;try{const out=await OutingsHost.cloud('outings',input);Object.assign(S,JSON.parse(OutingsHost.get('s3all-v1')));fuel=S.fuel;pts=S.merit;render();return out;}catch(e){toast(e.message,1);return null;}finally{outingBusy=false;}}
const HONEY_UI={jeep:{oil:300,hat:0,wait:20,merit:[300,600],chance:20},ship:{oil:100,hat:50,wait:10,merit:[800,1500],chance:25},raft:{oil:500,hat:100,wait:5,merit:[5000,10000],chance:30}};
let honeyOffset=0;
const honeyNow=()=>Date.now()+honeyOffset;
const honeyHour=()=>+new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',hour12:false}).format(new Date(honeyNow()));
const honeyOpen=v=>v==='jeep'||(v==='ship'?(honeyHour()>=18||honeyHour()<6):honeyHour()>=6&&honeyHour()<18);
const honeyFuel=()=>Math.min(100,(S.fuel||0)+Math.max(0,honeyNow()-(S.fuelAt??honeyNow()))*100/(4*3600000));
callHoney=async kind=>{const v=kind==='ship'||kind==='raft'?kind:'jeep';if(await outingAction({type:'call',vehicle:v})){closeAll();toast('🐷 น้องน้ำผึ้งกำลังมา');}};
renderHoney=function(){
 fuel=honeyFuel();$('fuelFill').style.width=fuel+'%';$('fuelTxt').textContent=Math.floor(fuel)+'%';
 const busy=!!S.honey&&hPhase()!=='gone';$('honeyNote').textContent=busy?'🐷 น้องน้ำผึ้งกำลังทำงานอยู่':'จี๊ปเรียกฟรีเมื่อแถบเต็ม (4 ชั่วโมง) หรือใช้น้ำมัน 300 แกลลอน';
 document.querySelectorAll('.hopt').forEach(b=>{const v=b.dataset.v,c=HONEY_UI[v],free=v==='jeep'&&fuel>=100;b.disabled=busy||!honeyOpen(v)||(!free&&(S.bag.item.fuel||0)<c.oil)||(S.bag.item.hat||0)<c.hat;
 b.querySelector('small').textContent=(v==='jeep'?'เปิดตลอดวัน':v==='ship'?'18:00–05:59':'06:00–17:59')+' · '+(free?'เรียกฟรี':'น้ำมัน '+c.oil)+(c.hat?' + หมวก '+c.hat:'')+' · รอ '+c.wait+' นาที';});
 if(!$('honeyCraft')){const d=document.createElement('div');d.id='honeyCraft';d.innerHTML='<button class="big" id="craftHoneyFuel">คราฟน้ำมัน</button> <button class="big" id="craftHoneyHat">คราฟหมวก</button>';$('honeySheet').appendChild(d);$('craftHoneyFuel').onclick=()=>honeyCraft('fuel');$('craftHoneyHat').onclick=()=>honeyCraft('hat');}
};
const honeyNeeds={fuel:[['bird','ostrich-egg',100,'ไข่นกกระจอกเทศ'],['bird','dodo-egg',100,'ไข่โดโด้'],['hedge','claw',100,'เล็บเม่น'],['product','roe',100,'ไข่ปลา'],['crop','corn',300,'ข้าวโพด'],['item','musicbox',10,'กล่องดนตรี'],['item','bell',5,'กระดิ่ง'],['sub','scarf-red',5,'ผ้าพันคอแดง']],hat:[['bird','dodo-feather',100,'ขนโดโด้สีรุ้ง'],['product','feather',100,'ขนไก่'],['sub','yarn-white',100,'ไหมพรมขาว'],['sub','yarn-blue',100,'ไหมพรมฟ้า'],['hedge','fang',100,'เขี้ยวเม่น']]};
function honeyCraft(recipe,q=1){const rows=honeyNeeds[recipe].map(([g,k,n,label])=>{const have=(g==='sub'?S.sub?.alpaca?.bag?.[k]:S.bag[g]?.[k])||0;return '<div class="dreq '+(have>=n*q?'ok':'no')+'"><b>'+label+'</b><span>'+have+'/'+n*q+'</span></div>';});closeAll();$('delSheet').innerHTML='<h3>คราฟ'+(recipe==='fuel'?'น้ำมัน':'หมวกกะลาสี')+'</h3><div class="hint">สำเร็จ '+(recipe==='fuel'?'100':'50')+'% · ได้ครั้งละ 10 · พลาดใช้วัตถุดิบ</div>'+rows.join('')+'<div class="hint"><button id="hcMinus">−</button> '+q+' ครั้ง <button id="hcPlus">＋</button></div><button class="big" id="hcGo">คราฟ</button>';open('delSheet');$('hcMinus').onclick=()=>honeyCraft(recipe,Math.max(1,q-1));$('hcPlus').onclick=()=>honeyCraft(recipe,Math.min(100,q+1));$('hcGo').onclick=async()=>{const out=await outingAction({type:'craft',recipe,quantity:q});if(out){toast('คราฟสำเร็จ '+out.crafted+' ครั้ง ได้ '+out.quantity+' ชิ้น');honeyCraft(recipe,q);}};}
openReq=function(){const h=S.honey;if(!h||h.leaveAt||hPhase()!=='parked')return;const c=HONEY_UI[h.v];$('delSheet').innerHTML='<h3>🐷 น้องน้ำผึ้งอยากได้…</h3>'+h.req.map(r=>'<div class="dreq '+(fHave(r)>=r[2]?'ok':'no')+'"><img src="'+fImg(r)+'"><b>'+fName(r)+'</b><span>มี '+fHave(r)+'/'+r[2]+'</span></div>').join('')+'<button class="big" id="sendHoney" '+(h.req.every(r=>fHave(r)>=r[2])?'':'disabled')+'>ส่งอาหาร</button><div class="hint">ลุ้นกุศล '+c.chance+'% ('+c.merit.join('–')+') หรือไอเทม 1 ประเภท</div>';open('delSheet');$('sendHoney').onclick=async()=>{const out=await outingAction({type:'deliver'});if(out){closeAll();render();const labels={angel:'ปีกนางฟ้า',cake:'เค้ก',coconut:'มะพร้าว',pestle:'สากกะเบือ',medicine:'ยาน้ำผึ้งมะนาว',hay:'ฟ่อนหญ้าหวาน',license:'ใบอนุญาต',musicbox:'กล่องดนตรี',bell:'กระดิ่ง',fuel:'น้ำมัน',hat:'หมวกกะลาสี','wool-gold':'ขนทองอัลปาก้า'};const items=Object.entries(out.items||{});toast(out.gain?'🐷 ได้ '+fmt(out.gain)+' กุศล':items.every(([k])=>k.startsWith('grass.'))?'🐷 ได้หญ้าครบ 5 สี สีละ '+items[0][1]:'🐷 ได้ '+items.map(([k,n])=>(labels[k.split('.').at(-1)]||'กล่องสุ่ม')+' ×'+n).join(', '));}};};
$('mHoney').onclick=()=>{closeAll();renderHoney();open('honeySheet');};
$('dFuel').onclick=()=>{closeAll();callHoney('jeep');};
setInterval(()=>{fuel=honeyFuel();},1000);
outingAction({type:'status'});
